FIX: fix 'EntityType' does not satisfy the constraint 'AnyObject' error
mswjs/data pull request #251
Opened 2022-11-17 22:58 UTC by imyasha

Issue: https://github.com/mswjs/data/issues/250

2022-11-20 21:26 UTC, kettanaito requested changes
Hey, @imyasha 👋 Thanks for opening this.

Looks like the build is failing. I suspect that the `AnyObject` type is not publicly exported by the library (it's internal) and thus certain types cannot compile? 

If you have a minute, could you take a look at what's going on? Thanks.

2022-11-22 02:34 UTC, imyasha commented
Hey, @kettanaito 
I was trying to export `AnyObject` but it doesn't solve the build error.
I think it's related with other thing.

Please take a look at it if you can.
Thanks

2023-01-24 15:32 UTC, cre8ive-gds commented on src/query/queryTypes.ts
> +  : ValueType extends Array<infer ItemType extends AnyObject>
```suggestion
  : ValueType extends Array<infer ItemType>
```

2023-01-24 16:10 UTC, kettanaito approved these changes
With @cre8ive-gds additions this looks good now! Thank you!

2023-01-24 16:10 UTC, merged

2023-01-24 23:19 UTC, kettanaito commented
## Released: v0.11.2 🎉

This has been released in v0.11.2!

- 📄 [**Release notes**](https://github.com/mswjs/data/releases/tag/v0.11.2)
- 📦 [npm package](https://www.npmjs.com/package/@mswjs/data/v/0.11.2)

Make sure to always update to the latest version (`npm i @mswjs/data@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.